[2024-05-08T03:25:12.535+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:25:12.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:25:12.567+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:25:12.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:25:13.359+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:25:13.325+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:25:13.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:25:13.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.970 seconds
[2024-05-08T03:26:19.170+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:26:19.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:26:19.228+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:26:19.227+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:26:20.810+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:26:20.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:26:20.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:26:21.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 1.881 seconds
[2024-05-08T03:26:52.177+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:26:52.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:26:52.195+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:26:52.191+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:26:52.318+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:26:52.299+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:26:52.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:26:52.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.279 seconds
[2024-05-08T03:27:23.107+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:27:23.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:27:23.115+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:27:23.115+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:27:23.192+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:27:23.184+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:27:23.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:27:23.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.128 seconds
[2024-05-08T03:27:53.512+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:27:53.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:27:53.517+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:27:53.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:27:53.604+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:27:53.593+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:27:53.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:27:53.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.140 seconds
[2024-05-08T03:28:23.872+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:28:23.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:28:23.881+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:28:23.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:28:23.949+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:28:23.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:28:23.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:28:23.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.132 seconds
[2024-05-08T03:28:54.497+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:28:54.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:28:54.502+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:28:54.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:28:54.565+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:28:54.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:28:54.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:28:54.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.116 seconds
[2024-05-08T03:29:25.253+0000] {processor.py:161} INFO - Started process (PID=493) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:29:25.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:29:25.258+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:29:25.258+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:29:25.329+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:29:25.319+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:29:25.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:29:25.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.115 seconds
[2024-05-08T03:29:56.041+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:29:56.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:29:56.048+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:29:56.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:29:56.120+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:29:56.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:29:56.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:29:56.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.126 seconds
[2024-05-08T03:30:26.814+0000] {processor.py:161} INFO - Started process (PID=615) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:30:26.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:30:26.819+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:30:26.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:30:26.903+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:30:26.890+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:30:26.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:30:26.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.166 seconds
[2024-05-08T03:30:57.557+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:30:57.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:30:57.564+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:30:57.564+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:30:57.648+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:30:57.637+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:30:57.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:30:57.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.137 seconds
[2024-05-08T03:31:27.937+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:31:27.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:31:27.952+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:31:27.950+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:31:28.145+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:31:28.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:31:28.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:31:28.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.340 seconds
[2024-05-08T03:31:59.076+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:31:59.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:31:59.128+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:31:59.127+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:32:00.722+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:32:00.528+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:32:00.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:32:00.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 1.957 seconds
[2024-05-08T03:32:35.080+0000] {processor.py:161} INFO - Started process (PID=841) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:32:35.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:32:35.166+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:32:35.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:32:35.400+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:32:35.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:32:35.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:32:35.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.450 seconds
[2024-05-08T03:33:05.793+0000] {processor.py:161} INFO - Started process (PID=901) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:33:05.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:33:05.801+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:33:05.801+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:33:05.921+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:33:05.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:33:05.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:33:05.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.186 seconds
[2024-05-08T03:33:37.578+0000] {processor.py:161} INFO - Started process (PID=959) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:33:37.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:33:37.644+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:33:37.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:33:38.228+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:33:38.133+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:33:38.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:33:38.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.832 seconds
[2024-05-08T03:41:51.829+0000] {processor.py:161} INFO - Started process (PID=1020) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:41:51.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:41:51.834+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:41:51.833+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:41:52.011+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:41:51.982+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:41:52.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:41:52.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.254 seconds
[2024-05-08T03:42:22.303+0000] {processor.py:161} INFO - Started process (PID=1075) to work on /opt/airflow/dags/mysql.py
[2024-05-08T03:42:22.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql.py for tasks to queue
[2024-05-08T03:42:22.307+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:42:22.307+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mysql.py
[2024-05-08T03:42:22.489+0000] {logging_mixin.py:188} INFO - [2024-05-08T03:42:22.468+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql.py", line 29, in <module>
    task1 = MySqlOperator(
            ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/operators/mysql.py", line 75, in __init__
    super().__init__(conn_id=mysql_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 242, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 892, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'create_a_table ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-05-08T03:42:22.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql.py
[2024-05-08T03:42:22.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql.py took 0.537 seconds
